spring.application.name=chatMemory
spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.model=stepfun/step-3.5-flash

logging.level.org.springframework.ai=DEBUG
logging.level.com.openai=DEBUG

logging.level.org.springframework.web.client=TRACE
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:h2:file:D://java//ai//chatMemory//chatmemorydb;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=dell@1234
spring.datasource.password=12345

