spring.application.name=bedrock

# properties to configure bedrock
spring.ai.bedrock.aws.region=${AWS_REGION}
spring.ai.bedrock.aws.access-key=${AWS_ACCESS_KEY}
spring.ai.bedrock.aws.secret-key=${AWS_SECRET_KEY}
spring.ai.model.chat=bedrock-converse
spring.ai.bedrock.converse.chat.model=minimax.minimax-m2.1
logging.level.org.springframework.ai=DEBUG
logging.level.com.openai=DEBUG

logging.level.org.springframework.web.client=TRACE
