spring.application.name=multiModel

# AI Provider Config
spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.model=stepfun/step-3.5-flash
spring.ai.chat.client.enabled=false

# properties to configure bedrock
spring.ai.bedrock.aws.region=${AWS_REGION}
spring.ai.bedrock.aws.access-key=${AWS_ACCESS_KEY}
spring.ai.bedrock.aws.secret-key=${AWS_SECRET_KEY}
spring.ai.bedrock.converse.chat.model=minimax.minimax-m2.1



logging.level.org.springframework.ai=DEBUG
logging.level.com.openai=DEBUG

logging.level.org.springframework.web.client=TRACE




logging.pattern.console=%highlight{%d{yyyy-MM-dd HH:mm:ss.SSS}} %highlight{%-5level} [%t] %highlight{%C{1.}} %highlight{%M} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%t] %C{1.} %M - %msg%n
